### ISSUE TITLE
Better video crash handling

### ISSUE THREAD

**Issue by vzjrz** [nkestrel/mediaurltimestamper#1] opened 2017-06-25 14:20 UTC
There is an unrelated bug I've experienced multiple times where you leave a youtube video paused for a really long time (hours) and when you come back and try to play it the video crashes and shows an error like shown here: https://productforums.google.com/forum/#!msg/youtube/5KjJz8mB5o4/G-Mq2A-lBwAJ
The problem is that mediaurltimestamper then resets the timestamp to 0:00 and loses the current saved time. Is there something that can be done like maybe only updating the timestamp when media is actively playing to prevent this?

**Comment by nkestrel** [comment] 2017-06-26 09:49
Good catch, probably a regression caused by 7e54d1aadc1b31be14507263f87774194faeb4ad.

**Comment by nkestrel** [comment] 2017-06-26 10:34
Should be fixed by eb491941520af46a13d6171338061278c61741ac.

**Closed as completed** 2017-06-26 10:41 UTC
Labels: bug
